name: coveralls
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
  
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1  # no history, just HEAD
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip install -r requirements.txt
    - name: Test with print
      run: |
        pwd
        coverage run -m pytest mapbox_data_download.py
    - name: Test with coveralls
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  
          MAT :${{ secrets.MAT }}  
          DATA :/home/runner/work/rural-school-mapper/rural-school-mapper/mapbox_test/
      run: |
        coveralls

     